apiVersion: apps/v1 
kind: Deployment
metadata:
  name: "$Username-docker-wine"
  labels:
    app: "$Username-docker-wine"
spec:
  selector:
    matchLabels:
      app: "$Username-docker-wine"
      client: $Username
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "$Username-docker-wine"
        client: $Username
    spec:
      containers:
      - image: scottyhardy/docker-wine
        name: "$Username-docker-wine"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "$MEM$mi"
            cpu: "$CPU$m"
        env:
        - name: RDP_SERVER
          value: "yes"
        - name: USER_NAME
          value: $Username
        - name: USER_PASSWD
          value: $Password
        volumeMounts:
        - name: $Username-docker-wine
          mountPath: /home
      volumes:
      - name: $Username-docker-wine
        persistentVolumeClaim:
          claimName: $Username-docker-wine
---
apiVersion: v1
kind: Service
metadata:
  name: "$Username-docker-wine"
  labels:
    app: "$Username-docker-wine"
spec:
  ports:
  - port: 3389
    protocol: TCP
    targetPort: 3389
  selector:
    app: "$Username-docker-wine"
    client: $Username
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $Username-docker-wine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
